// user types
export const LOADING_USER = 'LOADING_USER';
export const DONE_LOADING_USER = 'DONE_LOADING_USER';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED';
export const SET_USER_CREDENTIALS = 'SET_USER_CREDENTIALS';
export const SET_USER_NOTIFICATIONS = 'SET_USER_NOTIFICATIONS';
export const SET_USER_LIKES = 'SET_USER_LIKES';
export const SET_USER_IMAGE_URL = 'SET_USER_IMAGE_URL';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const ADD_USER_LIKE = 'ADD_USER_LIKE';
export const REMOVE_USER_LIKE = 'REMOVE_USER_LIKE';
export const ADD_USER_NOTIFICATION = 'ADD_USER_NOTIFICATION';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// ui types
export const LOADING_UI = 'LOADING_UI';
export const DONE_LOADING_UI = 'DONE_LOADING_UI';
export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// data types
export const LOADING_DATA = 'LOADING_DATA';
export const DONE_LOADING_DATA = 'DONE_LOADING_DATA';
export const SET_BLOGS = 'SET_BLOGS';
export const ADD_BLOG = 'ADD_BLOG';
export const REMOVE_BLOG = 'REMOVE_BLOG';
export const SET_BLOG_IMAGE_URL = 'SET_BLOG_IMAGE_URL';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EMPTY_COMMENTS = 'EMPTY_COMMENTS';
export const INCREMENT_LIKE = 'INCREMENT_LIKE';
export const DECREMENT_LIKE = 'DECREMENT_LIKE';
export const INCREMENT_COMMENT_COUNT = 'INCREMENT_COMMENT_COUNT';
// types format
export const type = 'type';